name: mlops
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - scikit-learn
  - pyyaml
  - python-dotenv
  - matplotlib
  - seaborn
  - mlflow
  - pytest
  - pytest-cov
  - pytest-mock
  - conda-forge::dvc-gdrive
