# Data paths
data:
  raw_data_path: "data/raw/diabetic_readmission_data.csv"
  processed_data_path: "data/processed"
  model_path: "models"
  test_data_path: "data/test"
  train_data_path: "data/processed/train.csv"
  validation_data_path: "data/processed/validation.csv"

# Database configuration
database:
  host: "localhost"
  port: 5432
  database: "mlops_db"
  user: "user"
  password: "password"

# Model parameters
model:
  name: "random_forest"
  random_state: 42
  test_size: 0.2
  validation_size: 0.1
  parameters:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1

# Feature engineering
features:
  target_column: "readmitted"
  age_bins: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
  age_labels:
    [
      "[0-10)",
      "[10-20)",
      "[20-30)",
      "[30-40)",
      "[40-50)",
      "[50-60)",
      "[60-70)",
      "[70-80)",
      "[80-90)",
      "[90-100)",
    ]
  los_bins: [0, 3, 7, 14, 30]
  los_labels: ["short", "medium", "long", "very_long"]
  n_features_to_select: 10
  categorical_features:
    - race
    - gender
    - age_group
  numerical_features:
    - age
    - time_in_hospital
    - num_lab_procedures
    - num_procedures
    - num_medications
    - number_outpatient
    - number_emergency
    - number_inpatient
    - number_diagnoses
  drop_columns:
    - "encounter_id"
    - "patient_nbr"
    - "diag_1"
    - "diag_2"
    - "diag_3"

# Preprocessing
preprocessing:
  scaling_method: "standard"
  encoding_method: "one_hot"
  handle_missing: "mean"
  feature_selection:
    method: "correlation"
    threshold: 0.1

# Training parameters
training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  early_stopping_patience: 10

# Evaluation metrics
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"
  cv_folds: 5

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/pipeline.log"

# Model registry
model_registry:
  type: "mlflow"
  tracking_uri: "http://localhost:5000"
  experiment_name: "diabetic_readmission_prediction"
